
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TaxCalculator", targetNamespace = "http://example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TaxCalculator {


    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculateTax", targetNamespace = "http://example.com/", className = "client.CalculateTax")
    @ResponseWrapper(localName = "calculateTaxResponse", targetNamespace = "http://example.com/", className = "client.CalculateTaxResponse")
    @Action(input = "http://example.com/TaxCalculator/calculateTaxRequest", output = "http://example.com/TaxCalculator/calculateTaxResponse")
    public double calculateTax(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

}
